### ISSUE TITLE
pushgateway看不到prometheus-pusher推送的metrics

### ISSUE THREAD

**Issue by zhaomeng-a** [yunlzheng/prometheus-pusher#1]
能看懂中文么？我就不写英语了。

我使用docker-compose启动的prometheus-pusher。而且prometheus和pushgateway都搭建成功，但不知道为什么pushgateway看不到prometheus-pusher推送的任何metrics，是pusher没有UI界面吗？怎么才能知道pusher有没有搭建成功？找了好久，也找不到原因。

**Comment by Vivian007** [comment]
这是我使用docker-compose搭建的pusher：（安装在与你的架构图对应的network2中)
![image](https://user-images.githubusercontent.com/29111297/29962341-8a07898c-8f35-11e7-8559-db0752181292.png)

启动：
![image](https://user-images.githubusercontent.com/29111297/29962407-bf28a70e-8f35-11e7-9e3c-b0048bba55a6.png)


这是pusher下面的Job/exporter：（同样安装在与你的架构图对应的network2中)
![image](https://user-images.githubusercontent.com/29111297/29962546-30bca2c6-8f36-11e7-995c-a470a1f0f13d.png)

然后我本地装了一个node_exporter:
![image](https://user-images.githubusercontent.com/29111297/29962631-6cd64d66-8f36-11e7-8d08-ddfed7f236ef.png)

不知道哪里还有问题、、

**Comment by Vivian007** [comment]
有没有日志之类的？在哪里可以查看……

**Comment by yunlzheng** [comment]
可以提供一下pusher容器的日志，我帮你看一下。

**Comment by Sunny-kubernetes** [comment]
部署文件如下：
```yaml
[root@prometheus pushgateway-pusher]# cat docker-compose.yml
version: '2'
services:
  prometheus-pusher:
    image: wisecity/prometheus-pusher:latest
    environment:
      PUSH_GATEWAY: http://192.168.10.30:9091
      TZ: Asia/Shanghai
    volumes:
    - ./prom-conf:/etc/prom-conf/
    ports:
    - "8080:8080"
    entrypoint:
    - /bin/prometheus_pusher
    - -config.file
    - /etc/prom-conf/prometheus.yml
```
目前我这边也看不到pushgateway上面的值。日志如下：
```shell
send data to pushgateway :http://192.168.10.30:9091/metrics/job/SqlMetrics/instance/192-168-10-20-9237-metrics
```
配置文件：
```yaml
cat prom-conf/prometheus.yml
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'exporter-metrics'

scrape_configs:
  - job_name: 'SqlMetrics'
    static_configs:
    - targets:
      - '192.168.10.20:9237'
```
sql_exporter 能收集到相关指标
```shell
[root@postgres-master mysql-exporter]# curl -s 192.168.10.20:9237/metrics |grep "ids"
sql_sql_queries{col="ids",database="mydb",driver="mysql",host="192.168.10.20:3306",sql_job="SqlMetrics",user="root"} 5
```
但是pushgateway上面没有将上述的指标推送到pushgateway

@yunlzheng 麻烦帮忙看看
