### ISSUE TITLE
prometheus-pusher无法将sql-exporter收集的数据推送到pushgateway上面

### ISSUE THREAD

**Issue by Sunny-kubernetes** [yunlzheng/prometheus-pusher#6]
图片如下：
![push](https://github.com/yunlzheng/prometheus-pusher/assets/136946258/07765c73-3ee7-40f2-9b2c-788856cb37e1)

部署文件如下：
```yaml
[root@prometheus pushgateway-pusher]# cat docker-compose.yml
version: '2'
services:
  prometheus-pusher:
    image: wisecity/prometheus-pusher:latest
    environment:
      PUSH_GATEWAY: http://192.168.10.30:9091
      TZ: Asia/Shanghai
    volumes:
    - ./prom-conf:/etc/prom-conf/
    ports:
    - "8080:8080"
    entrypoint:
    - /bin/prometheus_pusher
    - -config.file
    - /etc/prom-conf/prometheus.yml
```
目前我这边也看不到pushgateway上面的值。日志如下：
```bash
send data to pushgateway :http://192.168.10.30:9091/metrics/job/SqlMetrics/instance/192-168-10-20-9237-metrics
```
prometheus-pusher配置如下：
```yaml
cat prom-conf/prometheus.yml
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'exporter-metrics'

scrape_configs:
  - job_name: 'SqlMetrics'
    static_configs:
    - targets:
      - '192.168.10.20:9237'
```

sql-exporter采集数据如下：
```yaml
[root@postgres-master mysql-exporter]# curl -s 192.168.10.20:9237/metrics |grep "ids"
sql_sql_queries{col="ids",database="mydb",driver="mysql",host="192.168.10.20:3306",sql_job="SqlMetrics",user="root"} 5
```
但是pushgateway上面没有将上述的指标推送到pushgateway
@yunlzheng  麻烦帮忙看看
